# ----- BACKGROUND -----
background              #030826
background_opacity      0.40


# ----- WINDOW -----
remember_window_size    yes
initial_window_width    1900
initial_window_height   1050
start_as_fullscreen     no
hide_window_decorations yes


# ----- BORDER -----
window_border_width                    2px
draw_window_borders_for_single_window  yes
draw_minimal_borders                   no

window_margin_width                    2
single_window_margin_width             2

active_border_color                    #9d00ff
inactive_border_color                  #6a00a8


# ----- PADDING -----
window_padding_width                   8
single_window_padding_width            8


# ----- CURSOR -----
cursor                  #5710e6
cursor_text_color       #000000

cursor_trail            1
cursor_trail_decay      0.1 0.4
cursor_trail_start_threshold 1
cursor_trail_color      #5710e6


# ----- COLORS -----
foreground              #e6e6ff

selection_foreground    #030826
selection_background    #9d00ff

url_color               #00e5ff


# ----- COPY ON SELECT -----
copy_on_select yes
mouse_map right press ungrabbed paste_from_clipboard
