# Dark blue background
background              #030826

# Overall opacity (0 = transparent, 1 = opaque)
background_opacity      0.40

# Full screen without the top bar
remember_window_size    no
initial_window_width    1920
initial_window_height   1080
start_as_fullscreen     yes
hide_window_decorations yes

# Animated cursor
cursor #5710e6
cursor_text_color #000000

cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 1
cursor_trail_color #5710e6
