# Dark blue background
background              #1a1032

# Overall opacity (0 = transparent, 1 = opaque)
background_opacity      0.80

# Full screen without the top bar
remember_window_size    no
initial_window_width    1920
initial_window_height   1080
start_as_fullscreen     yes
hide_window_decorations yes
