# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path vers Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins Oh My Zsh
plugins=(
  git
  z
  sudo
  history
)

source $ZSH/oh-my-zsh.sh

# Improved history
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# Automatic correction of commands typed incorrectly
setopt CORRECT

# Practical aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'
alias grep='grep --color=auto'

# Basic custom - Alias
alias update='sudo apt update && sudo apt upgrade'
alias install='sudo apt install'
alias remove='sudo apt remove'
alias c='clear'
alias cat='batcat'
alias top='btop'

# Tree view shortcuts - Alias
alias docs='cd ~/Documents'
alias projets='cd ~/Documents/Projets'
alias techno='mpv --shuffle --loop-playlist ~/Musique/Techno/*.mp3'
alias chill='mpv --shuffle --loop-playlist ~/Musique/Chill/*.mp3'

# Configuration files - Alias
alias kittyconf='nano ~/.config/kitty/kitty.conf'
alias szsh='source ~/.zshrc'
alias gozsh='nano ~/.zshrc'

# Git - Alias
alias gs='git status'
alias ga='git add .'
alias gc='git commit -m'
alias gp='git push'
alias gpl='git pull'

gacp() {
  git add .
  git commit -m "$*"
  git push
}

# Scripts - Alias
invest() {
  cd /home/charly/Documents/Scripts/invest-tracker-tui || return 1
  go run .
}

# Dev python - Alias
alias p='python'
alias penv='python3 -m venv .venv && source .venv/bin/activate'
alias plib='pip install -r requirements.txt'
alias pinstall='pip install'
alias uvicorn='uvicorn main:app --reload'

# Dev nextjs - Alias
alias nextnew='npx create-next-app@latest'
alias studio='npx prisma studio'
alias sqlite3='nocorrect sqlite3'

# Prompt multicolor, more readable
autoload -U colors && colors

# Plugins
plugins=(
  git
  zsh-autosuggestions
)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export PATH=~/.npm-global/bin:$PATH
