# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path vers Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"

# Path et couleur de Kitty
export PATH="$HOME/.local/kitty.app/bin:$PATH"

# fzf avec fd (si installé)
export FZF_DEFAULT_COMMAND='find . -type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export PATH=$HOME/.local/bin:$PATH

# Thème : tu peux remplacer par "agnoster", "robbyrussell", ou "powerlevel10k/powerlevel10k" si installé
ZSH_THEME="powerlevel10k/powerlevel10k"

#Thème néon - https://github.com/Roboron3042/Cyberpunk-Neon/blob/master/terminal-apps/zsh/powerlevel9k
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time)
POWERLEVEL9K_CONTEXT_TEMPLATE=$'\ue795'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='#0abdc6'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='#321959'
POWERLEVEL9K_DIR_HOME_FOREGROUND='#0abdc6'
POWERLEVEL9K_DIR_HOME_BACKGROUND='#0b2956'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='#0abdc6'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='#0b2956'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='#0abdc6'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='#0b2956'
POWERLEVEL9K_DIR_ETC_FOREGROUND='#0abdc6'
POWERLEVEL9K_DIR_ETC_BACKGROUND='#0b2956'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#ea00d9'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='#321959'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#f57800'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='#321959'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#00ff00'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='#321959'
POWERLEVEL9K_STATUS_OK_BACKGROUND='#321959'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#ff0000'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='#321959'
POWERLEVEL9K_HISTORY_BACKGROUND='#0b2956'
POWERLEVEL9K_HISTORY_FOREGROUND='#0abdc6'
POWERLEVEL9K_TIME_BACKGROUND='#321959'
POWERLEVEL9K_TIME_FOREGROUND='#ea00d9'
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'

# Plugins Oh My Zsh
plugins=(
  git
  fzf
  z
  sudo
  history
)

source $ZSH/oh-my-zsh.sh

# Si fzf est installé depuis GitHub
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Historique amélioré
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# Correction automatique des commandes tapées avec faute
setopt CORRECT

# Active les alias avec sudo (ex: sudo ll)
alias sudo='sudo '

# Alias pratiques
alias ls='lsd'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'
alias grep='grep --color=auto'

# Basique custom - Alias
alias update='sudo apt update && sudo apt upgrade'
alias install='sudo apt install'
alias remove='sudo apt remove'
alias c='clear'
alias cat='batcat'
alias top='btop'

# Raccourcis arborescence - Alias
alias docs='cd ~/Documents'
alias projets='cd ~/Documents/Projets'
alias techno='mpv --shuffle --loop-playlist ~/Musique/Techno/*.mp3'
alias chill='mpv --shuffle --loop-playlist ~/Musique/Chill/*.mp3'

# Fichiers de config - Alias
alias kittyconf='nano ~/.config/kitty/kitty.conf'
alias szsh='source ~/.zshrc'
alias gozsh='nano ~/.zshrc'

# Git - Alias
alias gs='git status'
alias ga='git add .'
alias gc='git commit -m'
alias gp='git push'
alias gpl='git pull'

alias gacp='git add . && git commit -m "advancement" && git push'
alias g-refactor='git add . && git commit -m "refactoring" && git push'
alias g-bug='git add . && git commit -m "bug correction" && git push'
alias g-readme='git add . && git commit -m "readme" && git push'

# Dev python - Alias
alias penv='python3 -m venv .venv && source .venv/bin/activate'
alias plib='pip install -r requirements.txt'
alias pinstall='pip install'
alias unicorn='uvicorn main:app --reload'

# Dev nextjs - Alias
alias nextnew='npx create-next-app@latest'
alias nextdev='npm run dev'
alias nextbuild='npm run build'
alias studio='npx prisma studio'

# Crypto - Alias
alias crypto='cointop'

# Prompt multicouleur plus lisible (si pas de powerlevel10k)
autoload -U colors && colors

# Plugins
plugins=(
  git
  zsh-autosuggestions
)
